"""Is active

Revision ID: 2bdbc22717de
Revises: 5a8f818f40c0
Create Date: 2026-02-06 14:11:36.179407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bdbc22717de'
down_revision: Union[str, Sequence[str], None] = '5a8f818f40c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('is_active', sa.Boolean(), nullable=False, comment='Удалён ли объект'))
    op.create_index(op.f('ix_subjects_is_active'), 'subjects', ['is_active'], unique=False)
    op.create_unique_constraint(None, 'subjects', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subjects', type_='unique')
    op.drop_index(op.f('ix_subjects_is_active'), table_name='subjects')
    op.drop_column('subjects', 'is_active')
    # ### end Alembic commands ###
