"""Init Subjects

Revision ID: 5a8f818f40c0
Revises: 
Create Date: 2026-02-06 12:23:11.841525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a8f818f40c0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False, comment='Айди объекта'),
    sa.Column('length', sa.Float(), nullable=False, comment='Длинна объекта'),
    sa.Column('weight', sa.Float(), nullable=False, comment='Вес объекта'),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Время создания'),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Время обновления'),
    sa.Column('delete_at', sa.DateTime(), nullable=True, comment='Время удаления'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subjects')
    # ### end Alembic commands ###
